# Site
name: "OpenSquareD LAB"
title: "OSD LAB"
description: "OpenSquareD LAB"
logo: 'assets/images/logo.jpeg'
favicon: 'assets/images/logo.jpeg'
url: https://OpenSquareD.github.io/
baseurl: /
include: ["_pages"]
permalink: /:title/
email: opensquared.lab@gmail.com

# Authors
authors:
  OSD:
    name: OpenSquareD
    display_name: OSD
    email: opensquared.lab@gmail.com
    web: http://www.opensquared.org/
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [Gemfile, Gemfile.lock]
