# Site
name: "OpenSquareD LAB"
title: "OSD LAB"
description: "오픈스퀘어-D는 공공데이터에 대한 아이디어를 가진 사람들이 모여 경험과 기술을 서로 교류하고, 사업화와 창업으로 성장할 수 있도록 종합적으로 지원하는 공간입니다. 공공데이터 기반의 아이디어 구체화, 창업부터 지속성장까지, 공공데이터 활용 전(全)주기에 대한 지원 프로그램을 제공합니다."
logo: 'assets/images/logo.jpeg'
favicon: 'assets/images/logo.jpeg'
url: https://baem1n.github.io/
baseurl: /
include: ["_pages"]
permalink: /:title/
email: opensquared.lab@gmail.com

# Authors
authors:
  OSD:
    name: OpenSquareD
    display_name: OSD
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: opensquared.lab@gmail.com
    web: http://www.opensquared.org/
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [Gemfile, Gemfile.lock]
